module Phonofy
  VERSION: String

  class Error < StandardError
  end

  class << self
    attr_accessor configuration: Configuration
  end

  # These methods are already defined by the attr_accessor above

  def self.configure: () { (Configuration) -> void } -> void
  def self.config: () -> Configuration
end
